#!/bin/sh

uci -q batch <<'EOF'
set network.@device[0]=device
set network.@device[0].name='br-lan'
set network.@device[0].type='bridge'
delete network.@device[0].ports
add_list network.@device[0].ports='lan1'
add_list network.@device[0].ports='lan2'

set network.lan=interface
set network.lan.device='br-lan'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.20.1'
set network.lan.netmask='255.255.255.0'
delete network.lan.ip6assign
set network.lan.multipath='off'

set network.wan=interface
set network.wan.device='wan'
set network.wan.proto='pppoe'
set network.wan.username='__WAN1_USERNAME__'
set network.wan.password='__WAN1_PASSWORD__'
set network.wan.ipv6='0'
set network.wan.norelease='1'
set network.wan.metric='10'
set network.wan.multipath='off'

delete network.wan6

set network.wan2=interface
set network.wan2.device='lan3'
set network.wan2.proto='pppoe'
set network.wan2.username='__WAN2_USERNAME__'
set network.wan2.password='__WAN2_PASSWORD__'
set network.wan2.ipv6='0'
set network.wan2.norelease='1'
set network.wan2.metric='20'
set network.wan2.multipath='off'

set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_flags
delete dhcp.lan.ra_preference

set dhcp.wan=dhcp
set dhcp.wan.interface='wan'
set dhcp.wan.ignore='1'
set dhcp.wan2=dhcp
set dhcp.wan2.interface='wan2'
set dhcp.wan2.ignore='1'
set dhcp.odhcpd.maindhcp='0'

set mwan3.globals=globals
set mwan3.globals.mmx_mask='0x3F00'

set mwan3.wan=interface
set mwan3.wan.enabled='1'
set mwan3.wan.family='ipv4'
set mwan3.wan.reliability='1'
set mwan3.wan.count='1'
set mwan3.wan.timeout='2'
set mwan3.wan.interval='5'
set mwan3.wan.down='3'
set mwan3.wan.up='3'
delete mwan3.wan.track_ip
add_list mwan3.wan.track_ip='223.5.5.5'
add_list mwan3.wan.track_ip='119.29.29.29'
add_list mwan3.wan.track_ip='1.1.1.1'

set mwan3.wan2=interface
set mwan3.wan2.enabled='1'
set mwan3.wan2.family='ipv4'
set mwan3.wan2.reliability='1'
set mwan3.wan2.count='1'
set mwan3.wan2.timeout='2'
set mwan3.wan2.interval='5'
set mwan3.wan2.down='3'
set mwan3.wan2.up='3'
delete mwan3.wan2.track_ip
add_list mwan3.wan2.track_ip='223.5.5.5'
add_list mwan3.wan2.track_ip='119.29.29.29'
add_list mwan3.wan2.track_ip='1.1.1.1'

set mwan3.wan6=interface
set mwan3.wan6.enabled='0'
set mwan3.wan6.family='ipv6'

set mwan3.wan_m1_w1=member
set mwan3.wan_m1_w1.interface='wan'
set mwan3.wan_m1_w1.metric='1'
set mwan3.wan_m1_w1.weight='1'
set mwan3.wan2_m1_w1=member
set mwan3.wan2_m1_w1.interface='wan2'
set mwan3.wan2_m1_w1.metric='1'
set mwan3.wan2_m1_w1.weight='1'
set mwan3.wan_m2_w1=member
set mwan3.wan_m2_w1.interface='wan'
set mwan3.wan_m2_w1.metric='2'
set mwan3.wan_m2_w1.weight='1'
set mwan3.wan2_m2_w1=member
set mwan3.wan2_m2_w1.interface='wan2'
set mwan3.wan2_m2_w1.metric='2'
set mwan3.wan2_m2_w1.weight='1'

set mwan3.balanced=policy
delete mwan3.balanced.use_member
add_list mwan3.balanced.use_member='wan_m1_w1'
add_list mwan3.balanced.use_member='wan2_m1_w1'
set mwan3.wan_only=policy
set mwan3.wan_only.use_member='wan_m1_w1'
set mwan3.wan2_only=policy
set mwan3.wan2_only.use_member='wan2_m1_w1'
set mwan3.wan_wan2=policy
delete mwan3.wan_wan2.use_member
add_list mwan3.wan_wan2.use_member='wan_m1_w1'
add_list mwan3.wan_wan2.use_member='wan2_m2_w1'
set mwan3.wan2_wan=policy
delete mwan3.wan2_wan.use_member
add_list mwan3.wan2_wan.use_member='wan_m2_w1'
add_list mwan3.wan2_wan.use_member='wan2_m1_w1'

set mwan3.default_rule_v4=rule
set mwan3.default_rule_v4.dest_ip='0.0.0.0/0'
set mwan3.default_rule_v4.family='ipv4'
set mwan3.default_rule_v4.use_policy='balanced'

set firewall.@zone[1].network='wan wan2'
commit network
commit dhcp
commit mwan3
commit firewall
EOF

/etc/init.d/odhcpd disable >/dev/null 2>&1 || true
/etc/init.d/mwan3 enable >/dev/null 2>&1 || true

exit 0
